// Generated by TJC_Studio v1.6.0
#include "GeneratedUI.h"

GeneratedUI_page0::GeneratedUI_page0(TJC_Display& lcd)
    : title(lcd.text("tTitle", GeneratedUI_ID::Title)),
      value(lcd.number("nValue", GeneratedUI_ID::Value)),
      progress(lcd.progress("jProgress", GeneratedUI_ID::Progress)),
      start(lcd.button("bStart", GeneratedUI_ID::Start)),
      slider(lcd.slider("hSlider", GeneratedUI_ID::Slider)),
      bt0(lcd.dualButton("bt0", GeneratedUI_ID::Bt0))
{
}

GeneratedUI_page1::GeneratedUI_page1(TJC_Display& lcd)
{
}

GeneratedUI::GeneratedUI(TJC_Display& lcd)
    : page0(lcd),
      page1(lcd)
{
}
