// Generated by TJC_Studio v1.6.0
#ifndef GeneratedUI_H
#define GeneratedUI_H

#include <TJC_Display.h>

namespace GeneratedUI_ID
{
    constexpr uint8_t Title = 1;
    constexpr uint8_t Value = 2;
    constexpr uint8_t Progress = 3;
    constexpr uint8_t Start = 4;
    constexpr uint8_t Slider = 5;
    constexpr uint8_t Bt0 = 6;
}

class GeneratedUI_page0
{
public:
    explicit GeneratedUI_page0(TJC_Display& lcd);

    TJC_Text title;
    TJC_Number value;
    TJC_ProgressBar progress;
    TJC_Button start;
    TJC_Slider slider;
    TJC_DualButton bt0;
};

class GeneratedUI_page1
{
public:
    explicit GeneratedUI_page1(TJC_Display& lcd);

};

class GeneratedUI
{
public:
    explicit GeneratedUI(TJC_Display& lcd);

    GeneratedUI_page0 page0;
    GeneratedUI_page1 page1;
};

#endif // GeneratedUI_H
